Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import requests
r = requests.get('https://dmigw.govcloud.dk/v2/metObs/collections/station/items', params={'api-key': api_key})
stations = pd.json_normalize(r.json()['features'])
stations.columns = [c.replace('properties.', '').replace('geometry.', '') for c in stations.columns]

# Fileter out inactive stations
stations = stations[stations['status'] == 'Active']
# This line removes previous locations of the same station
# thus only the newest/current location is shown
stations = stations[stations['validTo'].isna()]
stations
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mrequests[39;00m
[1;32m      2[0m r [38;5;241m=[39m requests[38;5;241m.[39mget([38;5;124m'[39m[38;5;124mhttps://dmigw.govcloud.dk/v2/metObs/collections/station/items[39m[38;5;124m'[39m, params[38;5;241m=[39m{[38;5;124m'[39m[38;5;124mapi-key[39m[38;5;124m'[39m: api_key})
[0;32m----> 3[0m stations [38;5;241m=[39m [43mpd[49m[38;5;241m.[39mjson_normalize(r[38;5;241m.[39mjson()[[38;5;124m'[39m[38;5;124mfeatures[39m[38;5;124m'[39m])
[1;32m      4[0m stations[38;5;241m.[39mcolumns [38;5;241m=[39m [c[38;5;241m.[39mreplace([38;5;124m'[39m[38;5;124mproperties.[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m'[39m)[38;5;241m.[39mreplace([38;5;124m'[39m[38;5;124mgeometry.[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m'[39m) [38;5;28;01mfor[39;00m c [38;5;129;01min[39;00m stations[38;5;241m.[39mcolumns]
[1;32m      6[0m [38;5;66;03m# Fileter out inactive stations[39;00m

[0;31mNameError[0m: name 'pd' is not defined
NameError: name 'pd' is not defined

